omni_mulinex_joystick:
  ros__parameters:
    mode: "pan-tilt"
    timer_period_ms: 100
    sup_vel_x: 0.5
    sup_vel_y: 0.5
    sup_omega: 0.5
    sup_pan: 1.0
    sup_tilt: 0.5
    height_step: 0.005
    roll_step: 0.02
    pitch_step: 0.02
    yaw_step: 0.02
    pos_step: 0.005
    max_height: 0.15
    max_roll: 0.3
    max_pitch: 0.3
    max_yaw: 0.15
    max_pos_x: 0.05
    max_pos_y: 0.05
    deadzone: 0.1
    subscribe_state: true
